FROM golang:1.20.13-alpine

RUN apk add git alpine-sdk
RUN apk add linux-headers bash
RUN git clone https://github.com/dymensionxyz/dymension.git --branch 'fraud_proof_poc'

WORKDIR /go/dymension
RUN go mod tidy
RUN make install
RUN sh scripts/setup_local.sh
EXPOSE 36657

CMD ["dymd", "start"]
