FROM golang:1.20.13 AS builder

RUN git clone 'https://github.com/dymensionxyz/rollapp-evm.git' --branch 'feat/fraudproofs'
WORKDIR /go/rollapp-evm
RUN go mod tidy
RUN make install

WORKDIR /go
RUN apt update && apt install sudo jq -y

RUN curl -L https://dymensionxyz.github.io/roller/install.sh | bash
RUN git clone https://github.com/dymensionxyz/roller.git
WORKDIR /go/roller
RUN git checkout b4977ec4a6d9231fcd0c1ee1d869d5450665a75c
RUN make build
RUN mv build/roller /usr/local/bin

WORKDIR /go
COPY ./wait-for-hub.sh .
RUN sudo chmod +x ./wait-for-hub.sh

RUN rm -rf ./rollapp-evm/
RUN rm -rf ./roller/

FROM builder

# CACHEBUST invalidates the cache so that a new roller config is created on each build and new wallets are generated
# podman build -f Dockerfile.rollapp-evm --build-arg CACHEBUST=$(date +%s) -t dymension:fraud_proof_poc_rollapp
ARG CACHEBUST=1

ENV ROLLAPP_NAME "dummy"
ENV ROLLAPP_DENOM "dum"
ENV ROLLAPP_BINARY "/go/bin/rollapp-evm"

RUN ls -la /usr/local/bin
RUN roller config init ${ROLLAPP_NAME} ${ROLLAPP_DENOM} --hub local --da local --rollapp-binary ${ROLLAPP_BINARY} > rollapp_init
RUN sed -i 's/^batch_submit_max_time.*/batch_submit_max_time = "10s"/'  ~/.roller/rollapp/config/dymint.toml
RUN sed -i 's/^da_layer.*/da_layer = "grpc"/'  ~/.roller/rollapp/config/dymint.toml
RUN sed -i 's/^.*"min_gas_price".*/"min_gas_price": "0.0",/' ~/.roller/rollapp/config/genesis.json
RUN sed -i 's/^empty_blocks_max_time.*/empty_blocks_max_time = "2s"/'  ~/.roller/rollapp/config/dymint.toml
RUN sed -i 's/^da_config.*/da_config = "{\\\"host\\\": \\\"mock-da\\\", \\\"port\\\": 7980}"/'  ~/.roller/rollapp/config/dymint.toml
RUN roller config set hub-rpc "http://hub:36657"

CMD [ "sleep", "infinity" ]
