export BASE_DENOM="arax"
export BECH32_PREFIX=ethm
export CELESTIA_HOME_DIR="${HOME}/.da"
export CELESTIA_NETWORK="celestia" # for a testnet RollApp use "mocha", for mainnet - "celestia"
export DA_CLIENT="mock" # choose DA client: celestia, weavevm, next configuration can depends on it
export DENOM=$(echo "$BASE_DENOM" | sed 's/^.//')
export EXECUTABLE="rollapp-evm" # for rollapp
export HUB_CHAIN_ID="dymension_100-1"
export HUB_KEY_WITH_FUNDS="hub-user"
export HUB_PERMISSIONED_KEY="hub-user"
export HUB_REST_URL="http://localhost:1318" # required for relayer
export HUB_RPC_ENDPOINT="localhost"
export HUB_RPC_PORT="36657" # default: 36657
export HUB_RPC_URL="http://${HUB_RPC_ENDPOINT}:${HUB_RPC_PORT}"
export KEY_NAME_ROLLAPP="rol-user"
export MONIKER="$ROLLAPP_CHAIN_ID-sequencer"
export ROLLAPP_CHAIN_ID="rollappevm_1234-1"
export ROLLAPP_HOME_DIR="$HOME/.rollapp_evm"
export ROLLAPP_SETTLEMENT_INIT_DIR_PATH="${ROLLAPP_HOME_DIR}/init"
export SETTLEMENT_EXECUTABLE=$(which dymd)
export SETTLEMENT_LAYER="dymension" # when running a local hub or a public network use "dymension"
export SKIP_EVM_BASE_FEE=true # optional, disables rollapp fees
export HUB_FLAGS=(--from hub-user --fees 20000000000000adym -y)
export ETH_TOKEN_CONTRACT="0x934b867052ca9c65e33362112f35fb548f8732c2fe45f07b9c591958e865def0" # arb
export DST_DOMAIN=1 # arb
