run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - gofumpt
    - misspell
    - revive
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec

issues:
  exclude-use-default: false
  exclude:
    - "^.*SA1019.*$" # Excluding SA1019 errors

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: true
  errcheck:
    check-type-assertions: true
