# https://golangci-lint.run/usage/configuration

version: "2"

run:
  concurrency: 4
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    text:
      colors: true
      path: stdout
      print-issued-lines: true
      print-linter-name: true
  path-prefix: ""
  sort-order:
  - file
  - severity
  - linter

linters:
  default: none
  enable:
  - errcheck
  - gocyclo
  - gosec
  - govet
  - ineffassign
  - misspell
  - revive
  - staticcheck
  - unconvert
  - unused
  - errorlint
  exclusions:
    rules:
    - linters:
      - staticcheck
      text: "^.*SA1019.*$"
  settings:
    revive:
      rules:
      - name: exported
        severity: warning
        disabled: true
    errcheck:
      check-type-assertions: true

issues:
  uniq-by-line: true

formatters:
  enable:
  - goimports
  - gofumpt
