run:
  concurrency: 4
  timeout: 10m
  tests: false
  modules-download-mode: readonly

output:
  # The formats used to render issues.
  # Formats:
  # - `colored-line-number`
  # - `line-number`
  # - `json`
  # - `colored-tab`
  # - `tab`
  # - `html`
  # - `checkstyle`
  # - `code-climate`
  # - `junit-xml`
  # - `junit-xml-extended`
  # - `github-actions`
  # - `teamcity`
  # - `sarif`
  # Output path can be either `stdout`, `stderr` or path to the file to write to.
  formats:
    - format: colored-line-number
  # Default: true
  print-issued-lines: false
  # Print linter name in the end of issue text.
  # Default: true
  print-linter-name: true
  # Add a prefix to the output file references.
  # Default: ""
  path-prefix: ""
  # Sort results by: filepath, line and column.
  # Default: false
  sort-results: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - errorlint

issues:
  uniq-by-line: false
  exclude-use-default: false
  exclude:
    - "^.*SA1019.*$" # Excluding SA1019 errors

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: true
  errcheck:
    check-type-assertions: true
