// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dymensionxyz/dymension/incentives/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params holds parameters for the incentives module
type Params struct {
	// distr_epoch_identifier is what epoch type distribution will be triggered by
	// (day, week, etc.)
	DistrEpochIdentifier string `protobuf:"bytes,1,opt,name=distr_epoch_identifier,json=distrEpochIdentifier,proto3" json:"distr_epoch_identifier,omitempty" yaml:"distr_epoch_identifier"`
	// CreateGaugeBaseFee is a base fee required to create a new gauge. The final
	// fee is calculated as
	// Fee = CreateGaugeBaseFee + AddDenomFee * (len(Denoms) + len(GaugeDenoms)).
	CreateGaugeBaseFee cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=create_gauge_base_fee,json=createGaugeBaseFee,proto3,customtype=cosmossdk.io/math.Int" json:"create_gauge_base_fee"`
	// AddToGaugeBaseFee is a base fee required to add to gauge. The final
	// fee is calculated as
	// Fee = AddToGaugeBaseFee + AddDenomFee * len(Denoms).
	AddToGaugeBaseFee cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=add_to_gauge_base_fee,json=addToGaugeBaseFee,proto3,customtype=cosmossdk.io/math.Int" json:"add_to_gauge_base_fee"`
	// AddDenomFee is a fee charged for adding every new denom to the gauge.
	AddDenomFee cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=add_denom_fee,json=addDenomFee,proto3,customtype=cosmossdk.io/math.Int" json:"add_denom_fee"`
	// min_value_for_distribution is the minimum amount a token must be worth
	// in order to be eligible for distribution. If the token is worth
	// less than this amount (or the route between the two denoms is not
	// registered), it will not be distributed and is forfeited to the remaining
	// distributees that are eligible.
	MinValueForDistribution types.Coin `protobuf:"bytes,5,opt,name=min_value_for_distribution,json=minValueForDistribution,proto3" json:"min_value_for_distribution"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_256a114c8e13cfa0, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetDistrEpochIdentifier() string {
	if m != nil {
		return m.DistrEpochIdentifier
	}
	return ""
}

func (m *Params) GetMinValueForDistribution() types.Coin {
	if m != nil {
		return m.MinValueForDistribution
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*Params)(nil), "dymensionxyz.dymension.incentives.Params")
}

func init() {
	proto.RegisterFile("dymensionxyz/dymension/incentives/params.proto", fileDescriptor_256a114c8e13cfa0)
}

var fileDescriptor_256a114c8e13cfa0 = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x1b, 0x36, 0x26, 0xe1, 0x89, 0x03, 0xd1, 0x0a, 0x5d, 0x25, 0xd2, 0xad, 0xa7, 0x49,
	0x08, 0x5b, 0x63, 0x07, 0x24, 0x8e, 0x65, 0x0c, 0xf5, 0x04, 0x54, 0x08, 0x24, 0x04, 0x58, 0x4e,
	0xfc, 0x9a, 0x5a, 0xcc, 0x7e, 0x51, 0xec, 0x44, 0x0b, 0x9f, 0x82, 0x0f, 0xc3, 0x87, 0xd8, 0x8d,
	0x89, 0x13, 0xe2, 0x50, 0xa1, 0xf6, 0x1b, 0xf0, 0x09, 0x90, 0x93, 0x68, 0x2b, 0x88, 0x1d, 0x7a,
	0xcb, 0xf3, 0xff, 0xff, 0xff, 0xf9, 0xbd, 0xf8, 0x11, 0x2a, 0x2b, 0x0d, 0xc6, 0x2a, 0x34, 0x67,
	0xd5, 0x67, 0x76, 0x59, 0x30, 0x65, 0x12, 0x30, 0x4e, 0x95, 0x60, 0x59, 0x26, 0x72, 0xa1, 0x2d,
	0xcd, 0x72, 0x74, 0x18, 0xee, 0xaf, 0xfa, 0xaf, 0xc2, 0xf4, 0xca, 0xdf, 0xdf, 0x49, 0x31, 0xc5,
	0xda, 0xcd, 0xfc, 0x57, 0x13, 0xec, 0xef, 0x26, 0x68, 0x35, 0x5a, 0xde, 0x08, 0x4d, 0xd1, 0x4a,
	0x51, 0x53, 0xb1, 0x58, 0x58, 0x60, 0xe5, 0x61, 0x0c, 0x4e, 0x1c, 0xb2, 0x04, 0x95, 0x69, 0xf4,
	0xe1, 0xb7, 0x0d, 0xb2, 0xf5, 0xb2, 0x6e, 0x22, 0x7c, 0x4b, 0xee, 0x4a, 0x65, 0x5d, 0xce, 0x21,
	0xc3, 0x64, 0xc6, 0x95, 0xf4, 0x97, 0x4e, 0x15, 0xe4, 0xbd, 0x60, 0x2f, 0x38, 0xb8, 0x35, 0xda,
	0xff, 0x3d, 0x1f, 0xdc, 0xaf, 0x84, 0x3e, 0x7d, 0x32, 0xfc, 0xbf, 0x6f, 0x38, 0xd9, 0xa9, 0x85,
	0x67, 0xfe, 0x7c, 0x7c, 0x79, 0x1c, 0x7e, 0x24, 0xdd, 0x24, 0x07, 0xe1, 0x80, 0xa7, 0xa2, 0x48,
	0x81, 0xfb, 0x5e, 0xf8, 0x14, 0xa0, 0x77, 0xa3, 0xe6, 0x3e, 0x38, 0x9f, 0x0f, 0x3a, 0x3f, 0xe7,
	0x83, 0x6e, 0xd3, 0xaa, 0x95, 0x9f, 0xa8, 0x42, 0xa6, 0x85, 0x9b, 0xd1, 0xb1, 0x71, 0xdf, 0xbf,
	0x3e, 0x24, 0xed, 0x44, 0x63, 0xe3, 0x26, 0x61, 0x43, 0x7a, 0xee, 0x41, 0x23, 0x61, 0xe1, 0x04,
	0x20, 0xfc, 0x40, 0xba, 0x42, 0x4a, 0xee, 0xf0, 0x5f, 0xfe, 0xc6, 0xfa, 0xfc, 0x3b, 0x42, 0xca,
	0xd7, 0xf8, 0x17, 0xfe, 0x05, 0xb9, 0xed, 0xf1, 0x12, 0x0c, 0xea, 0x1a, 0xbb, 0xb9, 0x3e, 0x76,
	0x5b, 0x48, 0x79, 0xec, 0x01, 0x1e, 0xf8, 0x9e, 0xf4, 0xb5, 0x32, 0xbc, 0x14, 0xa7, 0x05, 0xf0,
	0x29, 0xe6, 0xbc, 0xfe, 0x6b, 0x2a, 0x2e, 0x9c, 0x42, 0xd3, 0xbb, 0xb9, 0x17, 0x1c, 0x6c, 0x3f,
	0xda, 0xa5, 0x6d, 0xda, 0x0f, 0x43, 0xdb, 0x87, 0xa3, 0x4f, 0x51, 0x99, 0xd1, 0xa6, 0xbf, 0x78,
	0x72, 0x4f, 0x2b, 0xf3, 0xc6, 0x13, 0x4e, 0x30, 0x3f, 0x5e, 0xc9, 0x8f, 0x5e, 0x9d, 0x2f, 0xa2,
	0xe0, 0x62, 0x11, 0x05, 0xbf, 0x16, 0x51, 0xf0, 0x65, 0x19, 0x75, 0x2e, 0x96, 0x51, 0xe7, 0xc7,
	0x32, 0xea, 0xbc, 0x7b, 0x9c, 0x2a, 0x37, 0x2b, 0x62, 0x9a, 0xa0, 0x66, 0xd7, 0xac, 0x66, 0x79,
	0xc4, 0xce, 0x56, 0xf7, 0xd3, 0x55, 0x19, 0xd8, 0x78, 0xab, 0xde, 0x95, 0xa3, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xa0, 0x29, 0xaf, 0x19, 0xd1, 0x02, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.MinValueForDistribution.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.AddDenomFee.Size()
		i -= size
		if _, err := m.AddDenomFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.AddToGaugeBaseFee.Size()
		i -= size
		if _, err := m.AddToGaugeBaseFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.CreateGaugeBaseFee.Size()
		i -= size
		if _, err := m.CreateGaugeBaseFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.DistrEpochIdentifier) > 0 {
		i -= len(m.DistrEpochIdentifier)
		copy(dAtA[i:], m.DistrEpochIdentifier)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DistrEpochIdentifier)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DistrEpochIdentifier)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = m.CreateGaugeBaseFee.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.AddToGaugeBaseFee.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.AddDenomFee.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MinValueForDistribution.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistrEpochIdentifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DistrEpochIdentifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateGaugeBaseFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CreateGaugeBaseFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddToGaugeBaseFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AddToGaugeBaseFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddDenomFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AddDenomFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinValueForDistribution", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinValueForDistribution.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
