// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dymensionxyz/dymension/streamer/stream.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Stream is an object that stores and distributes yields to recipients who
// satisfy certain conditions. Currently streams support conditions around the
// duration for which a given denom is locked.
type Stream struct {
	// id is the unique ID of a Stream
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// distribute_to is the distr_info.
	DistributeTo *DistrInfo `protobuf:"bytes,2,opt,name=distribute_to,json=distributeTo,proto3" json:"distribute_to,omitempty"`
	// coins is the total amount of coins that have been in the stream
	// Can distribute multiple coin denoms
	Coins github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=coins,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"coins"`
	// start_time is the distribution start time
	StartTime time.Time `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time" yaml:"start_time"`
	// distr_epoch_identifier is what epoch type di-stribution will be triggered by
	// (day, week, etc.)
	DistrEpochIdentifier string `protobuf:"bytes,5,opt,name=distr_epoch_identifier,json=distrEpochIdentifier,proto3" json:"distr_epoch_identifier,omitempty" yaml:"distr_epoch_identifier"`
	// num_epochs_paid_over is the number of total epochs distribution will be
	// completed over
	NumEpochsPaidOver uint64 `protobuf:"varint,6,opt,name=num_epochs_paid_over,json=numEpochsPaidOver,proto3" json:"num_epochs_paid_over,omitempty"`
	// filled_epochs is the number of epochs distribution has been completed on
	// already
	FilledEpochs uint64 `protobuf:"varint,7,opt,name=filled_epochs,json=filledEpochs,proto3" json:"filled_epochs,omitempty"`
	// distributed_coins are coins that have been distributed already
	DistributedCoins github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,8,rep,name=distributed_coins,json=distributedCoins,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"distributed_coins"`
	// Sponsored indicates if the stream is based on the sponsorship distribution.
	Sponsored bool `protobuf:"varint,9,opt,name=sponsored,proto3" json:"sponsored,omitempty"`
	// EpochCoins are coins that need to be distributed in this epoch.
	EpochCoins github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,10,rep,name=epoch_coins,json=epochCoins,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"epoch_coins"`
}

func (m *Stream) Reset()         { *m = Stream{} }
func (m *Stream) String() string { return proto.CompactTextString(m) }
func (*Stream) ProtoMessage()    {}
func (*Stream) Descriptor() ([]byte, []int) {
	return fileDescriptor_19586ad841c00cd9, []int{0}
}
func (m *Stream) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Stream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Stream.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Stream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stream.Merge(m, src)
}
func (m *Stream) XXX_Size() int {
	return m.Size()
}
func (m *Stream) XXX_DiscardUnknown() {
	xxx_messageInfo_Stream.DiscardUnknown(m)
}

var xxx_messageInfo_Stream proto.InternalMessageInfo

func (m *Stream) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Stream) GetDistributeTo() *DistrInfo {
	if m != nil {
		return m.DistributeTo
	}
	return nil
}

func (m *Stream) GetCoins() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Coins
	}
	return nil
}

func (m *Stream) GetStartTime() time.Time {
	if m != nil {
		return m.StartTime
	}
	return time.Time{}
}

func (m *Stream) GetDistrEpochIdentifier() string {
	if m != nil {
		return m.DistrEpochIdentifier
	}
	return ""
}

func (m *Stream) GetNumEpochsPaidOver() uint64 {
	if m != nil {
		return m.NumEpochsPaidOver
	}
	return 0
}

func (m *Stream) GetFilledEpochs() uint64 {
	if m != nil {
		return m.FilledEpochs
	}
	return 0
}

func (m *Stream) GetDistributedCoins() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.DistributedCoins
	}
	return nil
}

func (m *Stream) GetSponsored() bool {
	if m != nil {
		return m.Sponsored
	}
	return false
}

func (m *Stream) GetEpochCoins() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.EpochCoins
	}
	return nil
}

func init() {
	proto.RegisterType((*Stream)(nil), "dymensionxyz.dymension.streamer.Stream")
}

func init() {
	proto.RegisterFile("dymensionxyz/dymension/streamer/stream.proto", fileDescriptor_19586ad841c00cd9)
}

var fileDescriptor_19586ad841c00cd9 = []byte{
	// 533 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xcb, 0x6e, 0x13, 0x31,
	0x14, 0xcd, 0xa4, 0x4d, 0x68, 0x9c, 0x16, 0x11, 0x2b, 0x42, 0x43, 0x44, 0x67, 0x42, 0xd8, 0x8c,
	0x10, 0xd8, 0x7d, 0x88, 0x0d, 0xcb, 0x00, 0x8b, 0xae, 0x82, 0x86, 0x4a, 0x20, 0x36, 0x23, 0x4f,
	0xec, 0xa4, 0x16, 0x99, 0xf1, 0xc8, 0xf6, 0x44, 0x09, 0x5f, 0xd1, 0xef, 0xe0, 0x4b, 0xba, 0xec,
	0x12, 0x09, 0x29, 0x45, 0xc9, 0x1f, 0xf4, 0x0b, 0xd0, 0xd8, 0x79, 0x09, 0x51, 0x75, 0xd3, 0x55,
	0xec, 0x7b, 0xcf, 0x39, 0xf7, 0x9e, 0x93, 0x31, 0x78, 0x4d, 0xa7, 0x09, 0x4b, 0x15, 0x17, 0xe9,
	0x64, 0xfa, 0x03, 0xaf, 0x2f, 0x58, 0x69, 0xc9, 0x48, 0xc2, 0xe4, 0xf2, 0x80, 0x32, 0x29, 0xb4,
	0x80, 0xfe, 0x36, 0x1a, 0xad, 0x2f, 0x68, 0x85, 0x6e, 0x35, 0x87, 0x62, 0x28, 0x0c, 0x16, 0x17,
	0x27, 0x4b, 0x6b, 0x79, 0x43, 0x21, 0x86, 0x23, 0x86, 0xcd, 0x2d, 0xce, 0x07, 0x98, 0xe6, 0x92,
	0xe8, 0x82, 0x68, 0xfb, 0xfe, 0xbf, 0x7d, 0xcd, 0x13, 0xa6, 0x34, 0x49, 0xb2, 0x95, 0x40, 0x5f,
	0xa8, 0x44, 0x28, 0x1c, 0x13, 0xc5, 0xf0, 0xf8, 0x38, 0x66, 0x9a, 0x1c, 0xe3, 0xbe, 0xe0, 0x2b,
	0x81, 0xa3, 0xfb, 0x5c, 0x50, 0xae, 0xb4, 0x8c, 0x78, 0x3a, 0x58, 0xae, 0xd4, 0xf9, 0x5d, 0x01,
	0xd5, 0xcf, 0xa6, 0x0b, 0x1f, 0x83, 0x32, 0xa7, 0xae, 0xd3, 0x76, 0x82, 0xdd, 0xb0, 0xcc, 0x29,
	0xec, 0x81, 0x03, 0x03, 0xe7, 0x71, 0xae, 0x59, 0xa4, 0x85, 0x5b, 0x6e, 0x3b, 0x41, 0xfd, 0xe4,
	0x15, 0xba, 0xc7, 0x3c, 0xfa, 0x50, 0xb0, 0xce, 0xd2, 0x81, 0x08, 0xf7, 0x37, 0x02, 0xe7, 0x02,
	0x12, 0x50, 0x29, 0x76, 0x55, 0xee, 0x4e, 0x7b, 0x27, 0xa8, 0x9f, 0x3c, 0x43, 0xd6, 0x0d, 0x2a,
	0xdc, 0xa0, 0xa5, 0x1b, 0xf4, 0x5e, 0xf0, 0xb4, 0x7b, 0x74, 0x35, 0xf3, 0x4b, 0x3f, 0x6f, 0xfc,
	0x60, 0xc8, 0xf5, 0x45, 0x1e, 0xa3, 0xbe, 0x48, 0xf0, 0xd2, 0xba, 0xfd, 0x79, 0xa3, 0xe8, 0x77,
	0xac, 0xa7, 0x19, 0x53, 0x86, 0xa0, 0x42, 0xab, 0x0c, 0xbf, 0x02, 0xa0, 0x34, 0x91, 0x3a, 0x2a,
	0x92, 0x73, 0x77, 0xcd, 0xc2, 0x2d, 0x64, 0x63, 0x45, 0xab, 0x58, 0xd1, 0xf9, 0x2a, 0xd6, 0xee,
	0x61, 0x31, 0xe8, 0x76, 0xe6, 0x37, 0xa6, 0x24, 0x19, 0xbd, 0xeb, 0x6c, 0xb8, 0x9d, 0xcb, 0x1b,
	0xdf, 0x09, 0x6b, 0xa6, 0x50, 0xc0, 0xe1, 0x17, 0xf0, 0xd4, 0x86, 0xc7, 0x32, 0xd1, 0xbf, 0x88,
	0x38, 0x65, 0xa9, 0xe6, 0x03, 0xce, 0xa4, 0x5b, 0x69, 0x3b, 0x41, 0xad, 0xfb, 0xe2, 0x76, 0xe6,
	0x1f, 0x5a, 0x95, 0xff, 0xe3, 0x3a, 0x61, 0xd3, 0x34, 0x3e, 0x16, 0xf5, 0xb3, 0x75, 0x19, 0x62,
	0xd0, 0x4c, 0xf3, 0xc4, 0xc2, 0x55, 0x94, 0x11, 0x4e, 0x23, 0x31, 0x66, 0xd2, 0xad, 0x9a, 0x3f,
	0xa2, 0x91, 0xe6, 0x89, 0x61, 0xa8, 0x4f, 0x84, 0xd3, 0xde, 0x98, 0x49, 0xf8, 0x12, 0x1c, 0x0c,
	0xf8, 0x68, 0xc4, 0xe8, 0x92, 0xe3, 0x3e, 0x32, 0xc8, 0x7d, 0x5b, 0xb4, 0x60, 0x38, 0x01, 0x8d,
	0x4d, 0xf6, 0x34, 0xb2, 0xb9, 0xef, 0x3d, 0x7c, 0xee, 0x4f, 0xb6, 0xa6, 0x98, 0x0a, 0x7c, 0x0e,
	0x6a, 0x2a, 0x13, 0xa9, 0x12, 0x92, 0x51, 0xb7, 0xd6, 0x76, 0x82, 0xbd, 0x70, 0x53, 0x80, 0x23,
	0x50, 0xb7, 0xc1, 0xd8, 0x8d, 0xc0, 0xc3, 0x6f, 0x04, 0x8c, 0xbe, 0x39, 0x77, 0x7b, 0x57, 0x73,
	0xcf, 0xb9, 0x9e, 0x7b, 0xce, 0x9f, 0xb9, 0xe7, 0x5c, 0x2e, 0xbc, 0xd2, 0xf5, 0xc2, 0x2b, 0xfd,
	0x5a, 0x78, 0xa5, 0x6f, 0x6f, 0xb7, 0xf4, 0xee, 0x78, 0x34, 0xe3, 0x53, 0x3c, 0xd9, 0xbc, 0x1c,
	0x33, 0x22, 0xae, 0x9a, 0x6f, 0xe8, 0xf4, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x95, 0x10, 0x61,
	0xc8, 0x2f, 0x04, 0x00, 0x00,
}

func (m *Stream) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Stream) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Stream) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EpochCoins) > 0 {
		for iNdEx := len(m.EpochCoins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.EpochCoins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintStream(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if m.Sponsored {
		i--
		if m.Sponsored {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if len(m.DistributedCoins) > 0 {
		for iNdEx := len(m.DistributedCoins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DistributedCoins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintStream(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if m.FilledEpochs != 0 {
		i = encodeVarintStream(dAtA, i, uint64(m.FilledEpochs))
		i--
		dAtA[i] = 0x38
	}
	if m.NumEpochsPaidOver != 0 {
		i = encodeVarintStream(dAtA, i, uint64(m.NumEpochsPaidOver))
		i--
		dAtA[i] = 0x30
	}
	if len(m.DistrEpochIdentifier) > 0 {
		i -= len(m.DistrEpochIdentifier)
		copy(dAtA[i:], m.DistrEpochIdentifier)
		i = encodeVarintStream(dAtA, i, uint64(len(m.DistrEpochIdentifier)))
		i--
		dAtA[i] = 0x2a
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.StartTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.StartTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintStream(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x22
	if len(m.Coins) > 0 {
		for iNdEx := len(m.Coins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Coins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintStream(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.DistributeTo != nil {
		{
			size, err := m.DistributeTo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStream(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintStream(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintStream(dAtA []byte, offset int, v uint64) int {
	offset -= sovStream(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Stream) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovStream(uint64(m.Id))
	}
	if m.DistributeTo != nil {
		l = m.DistributeTo.Size()
		n += 1 + l + sovStream(uint64(l))
	}
	if len(m.Coins) > 0 {
		for _, e := range m.Coins {
			l = e.Size()
			n += 1 + l + sovStream(uint64(l))
		}
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovStream(uint64(l))
	l = len(m.DistrEpochIdentifier)
	if l > 0 {
		n += 1 + l + sovStream(uint64(l))
	}
	if m.NumEpochsPaidOver != 0 {
		n += 1 + sovStream(uint64(m.NumEpochsPaidOver))
	}
	if m.FilledEpochs != 0 {
		n += 1 + sovStream(uint64(m.FilledEpochs))
	}
	if len(m.DistributedCoins) > 0 {
		for _, e := range m.DistributedCoins {
			l = e.Size()
			n += 1 + l + sovStream(uint64(l))
		}
	}
	if m.Sponsored {
		n += 2
	}
	if len(m.EpochCoins) > 0 {
		for _, e := range m.EpochCoins {
			l = e.Size()
			n += 1 + l + sovStream(uint64(l))
		}
	}
	return n
}

func sovStream(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStream(x uint64) (n int) {
	return sovStream(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Stream) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStream
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Stream: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Stream: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributeTo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStream
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DistributeTo == nil {
				m.DistributeTo = &DistrInfo{}
			}
			if err := m.DistributeTo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStream
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Coins = append(m.Coins, types.Coin{})
			if err := m.Coins[len(m.Coins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStream
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistrEpochIdentifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStream
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DistrEpochIdentifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumEpochsPaidOver", wireType)
			}
			m.NumEpochsPaidOver = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumEpochsPaidOver |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FilledEpochs", wireType)
			}
			m.FilledEpochs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FilledEpochs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributedCoins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStream
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DistributedCoins = append(m.DistributedCoins, types.Coin{})
			if err := m.DistributedCoins[len(m.DistributedCoins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sponsored", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Sponsored = bool(v != 0)
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochCoins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStream
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStream
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStream
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EpochCoins = append(m.EpochCoins, types.Coin{})
			if err := m.EpochCoins[len(m.EpochCoins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStream(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStream
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStream(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStream
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStream
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStream
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStream
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStream
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStream
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStream        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStream          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStream = fmt.Errorf("proto: unexpected end of group")
)
