// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dymensionxyz/dymension/forward/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgFoo struct {
	Foo string `protobuf:"bytes,1,opt,name=foo,proto3" json:"foo,omitempty"`
}

func (m *MsgFoo) Reset()         { *m = MsgFoo{} }
func (m *MsgFoo) String() string { return proto.CompactTextString(m) }
func (*MsgFoo) ProtoMessage()    {}
func (*MsgFoo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7daab43adf05bc0, []int{0}
}
func (m *MsgFoo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFoo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFoo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFoo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFoo.Merge(m, src)
}
func (m *MsgFoo) XXX_Size() int {
	return m.Size()
}
func (m *MsgFoo) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFoo.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFoo proto.InternalMessageInfo

func (m *MsgFoo) GetFoo() string {
	if m != nil {
		return m.Foo
	}
	return ""
}

type MsgFooResponse struct {
}

func (m *MsgFooResponse) Reset()         { *m = MsgFooResponse{} }
func (m *MsgFooResponse) String() string { return proto.CompactTextString(m) }
func (*MsgFooResponse) ProtoMessage()    {}
func (*MsgFooResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7daab43adf05bc0, []int{1}
}
func (m *MsgFooResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFooResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFooResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFooResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFooResponse.Merge(m, src)
}
func (m *MsgFooResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgFooResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFooResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFooResponse proto.InternalMessageInfo

type MsgDemoHLToIBC struct {
	Signer string       `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	Hook   *HookHLtoIBC `protobuf:"bytes,2,opt,name=hook,proto3" json:"hook,omitempty"`
}

func (m *MsgDemoHLToIBC) Reset()         { *m = MsgDemoHLToIBC{} }
func (m *MsgDemoHLToIBC) String() string { return proto.CompactTextString(m) }
func (*MsgDemoHLToIBC) ProtoMessage()    {}
func (*MsgDemoHLToIBC) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7daab43adf05bc0, []int{2}
}
func (m *MsgDemoHLToIBC) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDemoHLToIBC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDemoHLToIBC.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDemoHLToIBC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDemoHLToIBC.Merge(m, src)
}
func (m *MsgDemoHLToIBC) XXX_Size() int {
	return m.Size()
}
func (m *MsgDemoHLToIBC) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDemoHLToIBC.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDemoHLToIBC proto.InternalMessageInfo

func (m *MsgDemoHLToIBC) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *MsgDemoHLToIBC) GetHook() *HookHLtoIBC {
	if m != nil {
		return m.Hook
	}
	return nil
}

type MsgDemoHLToIBCResponse struct {
}

func (m *MsgDemoHLToIBCResponse) Reset()         { *m = MsgDemoHLToIBCResponse{} }
func (m *MsgDemoHLToIBCResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDemoHLToIBCResponse) ProtoMessage()    {}
func (*MsgDemoHLToIBCResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7daab43adf05bc0, []int{3}
}
func (m *MsgDemoHLToIBCResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDemoHLToIBCResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDemoHLToIBCResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDemoHLToIBCResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDemoHLToIBCResponse.Merge(m, src)
}
func (m *MsgDemoHLToIBCResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDemoHLToIBCResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDemoHLToIBCResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDemoHLToIBCResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgFoo)(nil), "dymensionxyz.dymension.forward.MsgFoo")
	proto.RegisterType((*MsgFooResponse)(nil), "dymensionxyz.dymension.forward.MsgFooResponse")
	proto.RegisterType((*MsgDemoHLToIBC)(nil), "dymensionxyz.dymension.forward.MsgDemoHLToIBC")
	proto.RegisterType((*MsgDemoHLToIBCResponse)(nil), "dymensionxyz.dymension.forward.MsgDemoHLToIBCResponse")
}

func init() {
	proto.RegisterFile("dymensionxyz/dymension/forward/tx.proto", fileDescriptor_f7daab43adf05bc0)
}

var fileDescriptor_f7daab43adf05bc0 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4f, 0xa9, 0xcc, 0x4d,
	0xcd, 0x2b, 0xce, 0xcc, 0xcf, 0xab, 0xa8, 0xac, 0xd2, 0x87, 0x73, 0xf4, 0xd3, 0xf2, 0x8b, 0xca,
	0x13, 0x8b, 0x52, 0xf4, 0x4b, 0x2a, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0xe4, 0x90, 0x15,
	0xea, 0xc1, 0x39, 0x7a, 0x50, 0x85, 0x52, 0xe2, 0xc9, 0xf9, 0xc5, 0xb9, 0xf9, 0xc5, 0xfa, 0xb9,
	0xc5, 0xe9, 0xfa, 0x65, 0x86, 0x20, 0x0a, 0xa2, 0x51, 0x8a, 0x90, 0x0d, 0x29, 0x25, 0x10, 0x85,
	0x4a, 0x52, 0x5c, 0x6c, 0xbe, 0xc5, 0xe9, 0x6e, 0xf9, 0xf9, 0x42, 0x02, 0x5c, 0xcc, 0x69, 0xf9,
	0xf9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x20, 0xa6, 0x92, 0x00, 0x17, 0x1f, 0x44, 0x2e,
	0x28, 0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0xa9, 0x0c, 0x2c, 0xe2, 0x92, 0x9a, 0x9b, 0xef,
	0xe1, 0x13, 0x92, 0xef, 0xe9, 0xe4, 0x2c, 0x24, 0xc6, 0xc5, 0x56, 0x9c, 0x99, 0x9e, 0x97, 0x5a,
	0x04, 0xd5, 0x08, 0xe5, 0x09, 0xd9, 0x73, 0xb1, 0x64, 0xe4, 0xe7, 0x67, 0x4b, 0x30, 0x29, 0x30,
	0x6a, 0x70, 0x1b, 0x69, 0xeb, 0xe1, 0xf7, 0x88, 0x9e, 0x47, 0x7e, 0x7e, 0xb6, 0x87, 0x4f, 0x09,
	0xc8, 0xc8, 0x20, 0xb0, 0x46, 0x2b, 0xee, 0xa6, 0xe7, 0x1b, 0xb4, 0xa0, 0xa6, 0x29, 0x49, 0x70,
	0x89, 0xa1, 0xda, 0x0b, 0x73, 0x91, 0xd1, 0x23, 0x46, 0x2e, 0x66, 0xdf, 0xe2, 0x74, 0xa1, 0x58,
	0x2e, 0x66, 0x90, 0x27, 0xd4, 0x08, 0x59, 0x04, 0xf1, 0x90, 0x94, 0x1e, 0x71, 0xea, 0x60, 0xd6,
	0x08, 0x95, 0x72, 0x71, 0x23, 0xfb, 0x9a, 0x18, 0xed, 0x48, 0xea, 0xa5, 0xcc, 0x48, 0x53, 0x0f,
	0xb3, 0x56, 0x8a, 0xb5, 0xe1, 0xf9, 0x06, 0x2d, 0x46, 0x27, 0xbf, 0x13, 0x8f, 0xe4, 0x18, 0x2f,
	0x3c, 0x92, 0x63, 0x7c, 0xf0, 0x48, 0x8e, 0x71, 0xc2, 0x63, 0x39, 0x86, 0x0b, 0x8f, 0xe5, 0x18,
	0x6e, 0x3c, 0x96, 0x63, 0x88, 0x32, 0x49, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf,
	0xd5, 0xc7, 0x11, 0xe5, 0x65, 0xc6, 0xfa, 0x15, 0x88, 0x94, 0x55, 0x59, 0x90, 0x5a, 0x9c, 0xc4,
	0x06, 0x8e, 0x7b, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x63, 0xb8, 0x7c, 0x88, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	Foo(ctx context.Context, in *MsgFoo, opts ...grpc.CallOption) (*MsgFooResponse, error)
	DemoHLToIBC(ctx context.Context, in *MsgDemoHLToIBC, opts ...grpc.CallOption) (*MsgDemoHLToIBCResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Foo(ctx context.Context, in *MsgFoo, opts ...grpc.CallOption) (*MsgFooResponse, error) {
	out := new(MsgFooResponse)
	err := c.cc.Invoke(ctx, "/dymensionxyz.dymension.forward.Msg/Foo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DemoHLToIBC(ctx context.Context, in *MsgDemoHLToIBC, opts ...grpc.CallOption) (*MsgDemoHLToIBCResponse, error) {
	out := new(MsgDemoHLToIBCResponse)
	err := c.cc.Invoke(ctx, "/dymensionxyz.dymension.forward.Msg/DemoHLToIBC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	Foo(context.Context, *MsgFoo) (*MsgFooResponse, error)
	DemoHLToIBC(context.Context, *MsgDemoHLToIBC) (*MsgDemoHLToIBCResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) Foo(ctx context.Context, req *MsgFoo) (*MsgFooResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Foo not implemented")
}
func (*UnimplementedMsgServer) DemoHLToIBC(ctx context.Context, req *MsgDemoHLToIBC) (*MsgDemoHLToIBCResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DemoHLToIBC not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_Foo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgFoo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Foo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dymensionxyz.dymension.forward.Msg/Foo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Foo(ctx, req.(*MsgFoo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DemoHLToIBC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDemoHLToIBC)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DemoHLToIBC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dymensionxyz.dymension.forward.Msg/DemoHLToIBC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DemoHLToIBC(ctx, req.(*MsgDemoHLToIBC))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dymensionxyz.dymension.forward.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Foo",
			Handler:    _Msg_Foo_Handler,
		},
		{
			MethodName: "DemoHLToIBC",
			Handler:    _Msg_DemoHLToIBC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dymensionxyz/dymension/forward/tx.proto",
}

func (m *MsgFoo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFoo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFoo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Foo) > 0 {
		i -= len(m.Foo)
		copy(dAtA[i:], m.Foo)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Foo)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgFooResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFooResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFooResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDemoHLToIBC) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDemoHLToIBC) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDemoHLToIBC) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Hook != nil {
		{
			size, err := m.Hook.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDemoHLToIBCResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDemoHLToIBCResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDemoHLToIBCResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgFoo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Foo)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgFooResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDemoHLToIBC) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Hook != nil {
		l = m.Hook.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDemoHLToIBCResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgFoo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFoo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFoo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Foo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Foo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgFooResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFooResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFooResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDemoHLToIBC) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDemoHLToIBC: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDemoHLToIBC: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hook", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Hook == nil {
				m.Hook = &HookHLtoIBC{}
			}
			if err := m.Hook.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDemoHLToIBCResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDemoHLToIBCResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDemoHLToIBCResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
