name: E2E Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main

permissions:
  contents: read
  packages: write

jobs:
  test-ibc-transfer:
    runs-on: ubuntu-latest
    steps:
        - name: Check out the repo
          uses: actions/checkout@v3  
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
      
        - name: Build image
          id: build_image
          run: docker build . -t "ghcr.io/dymensionxyz/dymension:e2e" 

        - name: Set up Go 1.19
          uses: actions/setup-go@v3
          with:
            go-version: 1.19

        - run: make e2e-test-ibc
        - run: make e2e-test-ibc-timeout