name: markdown-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.2.0
        with:
          files: ./
          config_file: .markdownlint.yaml