# This workflow pushes new dymension images on every commit to main.
#
# ghcr.io/dymensionxyz/dymension:latest   # is updated 

name: Push docker images on new commit to main branch
on:
  push:
    branches:
      - main
  
permissions:
    contents: read
    packages: write
  
jobs:
    build-and-push:
      runs-on: ubuntu-latest
      steps:
        - 
          name: Check out the repo
          uses: actions/checkout@v3
        - 
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - 
          name: Build and push 
          id: build_push_image
          uses: docker/build-push-action@v3
          with:
            file: Dockerfile
            context: .
            push: true
            platforms: linux/amd64
            tags: |
                ghcr.io/dymensionxyz/dymension:latest